version: "3.4"

services:
  raidbot:
    build:
      context: ./PokemonRaidBot/
    ports:
      - 8088:80
    depends_on:
      - raidbot-db
    restart: always
    volumes:
      - ./PokemonRaidBot/config/:/var/www/html/config/
      - ./PokemonRaidBot/access/:/var/www/html/access/
      - ./PokemonRaidBot/custom/:/var/www/html/custom/
      - ./PokemonRaidBot/images/pokemon/:/var/www/html/images/pokemon/
      - ./tg-logs/:/var/log/tg-bots/
    environment:
      # Cleanup-Job every 5 min. https://github.com/florianbecker/PokemonRaidBot#cleanup
      CRON_USER_1: root
      CRON_SCHEDULE_1: */5 * * * *
      CRON_COMMAND_1: /usr/bin/curl -s -k -d '{"cleanup":{"secret":"changeme"}}' http://localhost/index.php?apikey=changeme
      # Raid-Overview Update every minute https://github.com/florianbecker/PokemonRaidBot#raid-overview
      CRON_USER_2: root
      CRON_SCHEDULE_2: * * * * *
      CRON_COMMAND_2: /usr/bin/curl -s -k -d '{"callback_query":{"data":"0:overview_refresh:0"}}' http://localhost/index.php?apikey=changeme
      TEMPLATE_PHP_INI: production
      PHP_INI_EXTENSION: gd

  raidbot-db:
    image: mariadb:10.3
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./raidbot-db/:/var/lib/mysql/
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: raidbot
      MYSQL_USER: changeme
      MYSQL_PASSWORD: changeme
